import fs from 'node:fs'
import path from 'node:path'
import { Piscina } from 'piscina'

export const DEFAULT_OUT_FILE_PATH = './src/generated/nest-component-scan.ts'
export const DEFAULT_IMPORT_EXTENSION = '.js'

const WORKER_MAIN_FILE_PATH = path.resolve(
  import.meta.dirname,
  './worker/main.js',
)

export type ImportExtension = string | null

export async function ensureOutDirPath(outFilePath: string): Promise<string> {
  const outDirPath = path.dirname(outFilePath)

  await fs.promises.mkdir(outDirPath, { recursive: true })

  return outDirPath
}

export interface WorkerInput {
  sourceFilePath: string
  outDirPath: string
  importExtension: ImportExtension
}

export type ComponentKind = 'controller' | 'injectable'

export interface ComponentInfo {
  kind: ComponentKind
  name: string
  importLine: string
}

export type WorkerOutput = ComponentInfo[]

export function createWorkerPool(): Piscina<WorkerInput, WorkerOutput> {
  return new Piscina<WorkerInput, WorkerOutput>({
    filename: WORKER_MAIN_FILE_PATH,
  })
}

export async function generateFile(input: {
  componentInfos: ComponentInfo[]
  outFilePath: string
}): Promise<void> {
  const { componentInfos, outFilePath } = input

  const importLines = componentInfos.map((x) => x.importLine)
  importLines.sort()

  const controllerLines = componentInfos
    .filter((x) => x.kind === 'controller')
    .map((x) => `  ${x.name},`)
  controllerLines.sort((a, b) => a.localeCompare(b))

  const injectableLines = componentInfos
    .filter((x) => x.kind === 'injectable')
    .map((x) => `  ${x.name},`)
  injectableLines.sort((a, b) => a.localeCompare(b))

  const lines: string[] = [
    '/* eslint-disable */',
    '',
    '// This file was automatically generated by nest-component-scan.',
    '',
    ...importLines,
    '',
    'export const SCANNED_CONTROLLERS = [',
    ...controllerLines,
    '];',
    '',
    'export const SCANNED_INJECTABLES = [',
    ...injectableLines,
    '];',
    '',
  ]

  await fs.promises.writeFile(outFilePath, lines.join('\n'))

  console.log(`${new Date().toISOString()} ${outFilePath} generated.`)
}
