import fs from 'node:fs'
import path from 'node:path'
import Piscina from 'piscina'

export type ImportExtension = string | null

export const DEFAULT_OUT_FILE = './src/generated/nest-component-scan.ts'
export const DEFAULT_IMPORT_EXTENSION = '.js'

export interface WorkerInput {
  sourceFile: string
  outDir: string
  importExtension: ImportExtension
}

export type ComponentKind = 'controller' | 'injectable'

export interface Component {
  kind: ComponentKind
  name: string
  importLine: string
}

export interface WorkerOutput {
  components: Component[]
}

export function createWorkerPool(): Piscina<WorkerInput, WorkerOutput> {
  return new Piscina<WorkerInput, WorkerOutput>({
    filename: path.resolve(__dirname, 'worker.js'),
  })
}

export async function generateFile(input: {
  components: Component[]
  outFile: string
}): Promise<void> {
  const { components, outFile } = input

  const importLines = components.map((x) => x.importLine).toSorted()

  const controllerLines = components
    .filter((x) => x.kind === 'controller')
    .toSorted((a, b) => a.name.localeCompare(b.name))
    .map((x) => `  ${x.name},`)

  const injectableLines = components
    .filter((x) => x.kind === 'injectable')
    .toSorted((a, b) => a.name.localeCompare(b.name))
    .map((x) => `  ${x.name},`)

  const lines: string[] = [
    '/* eslint-disable */',
    '',
    '// This file was automatically generated by nest-component-scan.',
    '',
    ...importLines,
    '',
    'export const SCANNED_CONTROLLERS = [',
    ...controllerLines,
    '];',
    '',
    'export const SCANNED_INJECTABLES = [',
    ...injectableLines,
    '];',
    '',
  ]

  await fs.promises.writeFile(outFile, lines.join('\n'))
}
